## creation.r
##   - Functions for creating new GP individuals (individual initialization)
##
## RGP - a GP system for R
## 2010 Oliver Flasch (oliver.flasch@fh-koeln.de)
## with contributions of Thomas Bartz-Beielstein, Olaf Mersmann and Joerg Stork
## released under the GPL v2
##

##' Creates an R expression by random growth
##'
##' Creates a random R expression by randomly growing its tree. In each step of growth,
##' with probability \code{subtreeprob}, an operator is chosen from the function set \code{funcset}.
##' The operands are then generated by recursive calls. If no subtree is generated, a constant will
##' be generated with probability \code{constprob}. If no constant is generated, an input variable
##' will be chosen randomly. The resulting expression trees can be bounded by the
##' \code{maxdepth} parameter.
##'
##' @param funcset The function set.
##' @param inset The set of input variables.
##' @param maxdepth The maximum expression tree depth.
##' @param constprob The probability of generating a constant in a step of growth, if no subtree
##'   is generated. If neither a subtree nor a constant is generated, a randomly chosen input variable
##'   will be generated.
##' @param subtreeprob The probability of generating a subtree in a step of growth. 
##' @param constfactory The factory function for constants. This function is called without any
##'   arguments when a constant has to be generated.
##' @return A new R expression generated by random growth.
##' @export
randexprGrow <- function(funcset, inset,
                         maxdepth = 16,
                         constprob = 0.5, subtreeprob = 0.5,
                         constfactory = function() runif(1, -1, 1),
                         curdepth = 1) {
  if (curdepth >= maxdepth) {
    if (runif(1) <= constprob) constfactory() else randelt(inset)
  } else {
  	if (runif(1) <= subtreeprob) {
  	  # create subtree
      funcname <- randelt(funcset)
      funcarity <- arity(funcname)
      as.call(append(funcname,
                     tabulateList(function(i) randexprGrow(funcset, inset, maxdepth,
                                                           constprob, subtreeprob, constfactory, curdepth + 1),
                                  funcarity)))
    } else {
      # create terminal
  	  if (runif(1) <= constprob) constfactory() else randelt(inset)
    }
  }
}

##' Creates an R expression by random growth to full depth
##'
##' Creates a random full expression tree of depth \code{depth}. The strategy is the same as
##' described in \code{\link{randexprGrow}}, with the exception that the probability of generating
##' a subtree is fixed to 1 until the desired tree depth \code{depth} is reached.
##'
##' @param funcset The function set.
##' @param inset The set of input variables.
##' @param depth The depth of the full tree to create.
##' @param constprob The probability of generating a constant at the deepest tree level. If no
##'   constant is generated, a randomly chosen input variable will be generated.
##' @param constfactory The factory function for constants. This function is called without any
##'   arguments when a constant has to be generated.
##' @return A new fully grown random R expression.
##' @export
randexprFull <- function(funcset, inset,
                         depth = 16,
                         constprob = 0.5,
                         constfactory = function() runif(1, -1, 1)) {
  randexprGrow(funcset, inset, depth, constprob, 1.0, constfactory)
}

##' Creates an R function with a random expression as its body
##'
##' @param funcset The function set.
##' @param inset The set of input variables.
##' @param maxdepth The maximum expression tree depth.
##' @param exprfactory The function to use for randomly creating the function's body.
##' @return A randomly generated R function.
##' @export
randfunc <- function(funcset, inset, maxdepth = 16, exprfactory = randexprGrow) {
  newf <- new.function()
  formals(newf) <- new.alist(inset)
  body(newf) <- exprfactory(funcset, inset, maxdepth)
  newf
}
